-- Run in Snowflake

CREATE DATABASE IF NOT EXISTS FINANCIAL_DATA;

CREATE SCHEMA IF NOT EXISTS FINANCIAL_DATA.RAW;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_DATA.STAGING;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_DATA.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_DATA.MARTS;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_DATA.AUDIT;

