-- Run in Snowflake

CREATE ROLE IF NOT EXISTS FDP_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS FDP_INGEST_ROLE;
CREATE ROLE IF NOT EXISTS FDP_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS FDP_REPORTING_ROLE;
CREATE ROLE IF NOT EXISTS FDP_AUDIT_ROLE;

GRANT USAGE ON DATABASE FINANCIAL_DATA TO ROLE FDP_INGEST_ROLE;
GRANT USAGE ON DATABASE FINANCIAL_DATA TO ROLE FDP_TRANSFORM_ROLE;
GRANT USAGE ON DATABASE FINANCIAL_DATA TO ROLE FDP_REPORTING_ROLE;
GRANT USAGE ON DATABASE FINANCIAL_DATA TO ROLE FDP_AUDIT_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE FINANCIAL_DATA TO ROLE FDP_INGEST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FINANCIAL_DATA TO ROLE FDP_TRANSFORM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FINANCIAL_DATA TO ROLE FDP_REPORTING_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FINANCIAL_DATA TO ROLE FDP_AUDIT_ROLE;

GRANT USAGE ON WAREHOUSE FDP_DEV_WH TO ROLE FDP_INGEST_ROLE;
GRANT USAGE ON WAREHOUSE FDP_TRANSFORM_WH TO ROLE FDP_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE FDP_TRANSFORM_WH TO ROLE FDP_REPORTING_ROLE;
GRANT USAGE ON WAREHOUSE FDP_DEV_WH TO ROLE FDP_AUDIT_ROLE;

GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA FINANCIAL_DATA.RAW TO ROLE FDP_INGEST_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FINANCIAL_DATA.STAGING TO ROLE FDP_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FINANCIAL_DATA.INTERMEDIATE TO ROLE FDP_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FINANCIAL_DATA.MARTS TO ROLE FDP_TRANSFORM_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA FINANCIAL_DATA.AUDIT TO ROLE FDP_AUDIT_ROLE;

