-- Run in Snowflake

CREATE FILE FORMAT IF NOT EXISTS FINANCIAL_DATA.RAW.JSON_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
  COMPRESSION = AUTO;

CREATE FILE FORMAT IF NOT EXISTS FINANCIAL_DATA.RAW.CSV_FORMAT
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE
  COMPRESSION = AUTO;

CREATE FILE FORMAT IF NOT EXISTS FINANCIAL_DATA.RAW.PARQUET_FORMAT
  TYPE = PARQUET
  COMPRESSION = AUTO;

