-- Run in Snowflake

CREATE STAGE IF NOT EXISTS FINANCIAL_DATA.RAW.FDP_GOLD_STAGE
  STORAGE_INTEGRATION = FDP_S3_INT
  URL = 's3://<data-lake-bucket>/batch/gold/'
  FILE_FORMAT = FINANCIAL_DATA.RAW.PARQUET_FORMAT;

CREATE STAGE IF NOT EXISTS FINANCIAL_DATA.RAW.FDP_STREAM_GOLD_STAGE
  STORAGE_INTEGRATION = FDP_S3_INT
  URL = 's3://<data-lake-bucket>/streaming/gold/'
  FILE_FORMAT = FINANCIAL_DATA.RAW.PARQUET_FORMAT;

