-- Run in Snowflake

SELECT
  'FACT_TRANSACTION' AS dataset_name,
  (SELECT COUNT(*) FROM FINANCIAL_DATA.RAW.FACT_TRANSACTION_LANDING) AS raw_row_count,
  (SELECT COUNT(*) FROM FINANCIAL_DATA.STAGING.FACT_TRANSACTION) AS staging_row_count,
  ABS(
    (SELECT COUNT(*) FROM FINANCIAL_DATA.RAW.FACT_TRANSACTION_LANDING) -
    (SELECT COUNT(*) FROM FINANCIAL_DATA.STAGING.FACT_TRANSACTION)
  ) AS row_count_difference;

