apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: financial-data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: financial-data-platform-airflow:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: fdp-config
          command:
            - bash
            - -lc
            - airflow scheduler

