version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: risk_score
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
  - name: stg_accounts
    columns:
      - name: account_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: stg_transactions
    columns:
      - name: transaction_id
        tests: [not_null, unique]
      - name: account_id
        tests:
          - relationships:
              to: ref('stg_accounts')
              field: account_id
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: currency_code
        tests:
          - accepted_values:
              values: ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD']
      - name: transaction_amount
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
  - name: stg_daily_balances
    columns:
      - name: balance_id
        tests: [not_null, unique]
