VALID_CURRENCY_CODES = {"USD", "EUR", "GBP", "JPY", "CAD", "AUD"}
INVALID_CURRENCY_CODE = "ZZZ"
VALID_TRANSACTION_STATUSES = {"PENDING", "POSTED", "FAILED", "REVERSED"}
VALID_TRANSACTION_TYPES = {"DEBIT", "CREDIT", "FEE", "REFUND", "WIRE", "ACH"}
VALID_PAYMENT_STATUSES = {"PENDING", "SETTLED", "FAILED", "CANCELLED"}
VALID_TRADE_SIDES = {"BUY", "SELL"}
COUNTRY_CODES = ["US", "GB", "DE", "CA", "AU", "JP"]
MERCHANT_CATEGORIES = [
    "GROCERY",
    "TRAVEL",
    "UTILITIES",
    "DINING",
    "PAYROLL",
    "BROKERAGE",
    "HEALTHCARE",
]
SECURITY_TYPES = ["EQUITY", "ETF", "BOND", "OPTION"]

